### ISSUE TITLE
PSFalcon Module Version 2.1.5 - Get-FalconQueue error at run

### ISSUE THREAD

**Issue by WEX-RMishler** [CrowdStrike/psfalcon#145]
Getting an error with this Version when attempting to run Command: Get-FalconQueue. 
$ get-falconqueue
Exception: C:\Users\x-rmishler\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1:36
Line |
  36 |              $Sessions = Get-FalconSession @SessionParam | Select-Obje …
     |                                            ~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Filter'. '(deleted_at:null' is not a valid Falcon Query Language statement.

Get-Error Details: 
$ get-error

Exception             :
    Type                        : System.Management.Automation.ParameterBindingValidationException
    Message                     : Cannot validate argument on parameter 'Filter'. '(deleted_at:null' is not a valid Falcon Query Language statement.
    ParameterName               : Filter
    ParameterType               : string
    TypeSpecified               : string
    ErrorId                     : ParameterArgumentValidationError
    Line                        : 36
    Offset                      : 43
    CommandInvocation           :
        MyCommand        : Get-FalconSession
        ScriptLineNumber : 36
        OffsetInLine     : 25
        HistoryId        : 57
        ScriptName       : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1
        Line             : $Sessions = Get-FalconSession @SessionParam | Select-Object id, device_id

        PositionMessage  : At C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1:36 char:25
                           +             $Sessions = Get-FalconSession @SessionParam | Select-Obje …
                           +                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        PSScriptRoot     : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public
        PSCommandPath    : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1
        InvocationName   : Get-FalconSession
        PipelineLength   : 2
        PipelinePosition : 1
        CommandOrigin    : Internal
    ErrorRecord                 :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot validate argument on parameter 'Filter'. '(deleted_at:null' is not a valid Falcon Query Language statement.
            HResult : -2146233087
        CategoryInfo          : InvalidData: (:) [Get-FalconSession], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ParameterArgumentValidationError,Get-FalconSession
        InvocationInfo        :
            MyCommand        : Get-FalconSession
            ScriptLineNumber : 36
            OffsetInLine     : 43
            HistoryId        : 57
            ScriptName       : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1
            Line             : $Sessions = Get-FalconSession @SessionParam | Select-Object id, device_id

            PositionMessage  : At C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1:36 char:43
                               +             $Sessions = Get-FalconSession @SessionParam | Select-Obje …
                               +                                           ~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public
            PSCommandPath    : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Get-FalconQueue<Process>, C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1: line 36
                                at <ScriptBlock>, <No file>: line 1
    WasThrownFromThrowStatement : True
    TargetSite                  :
        Name          : CheckActionPreference
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.2.0.500, Culture=neutral, PublicKeyToken=<Obscured>
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data                        : System.Collections.ListDictionaryInternal
    InnerException              :
        Type                        : System.Management.Automation.RuntimeException
        ErrorRecord                 :
            Exception             :
                Type                        : System.Management.Automation.RuntimeException
                ErrorRecord                 :
                    Exception             :
                        Type    : System.Management.Automation.ParentContainsErrorRecordException
                        Message : '(deleted_at:null' is not a valid Falcon Query Language statement.
                        HResult : -2146233087
                    CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
                    FullyQualifiedErrorId : RuntimeException
                WasThrownFromThrowStatement : True
                Message                     : '(deleted_at:null' is not a valid Falcon Query Language statement.
                HResult                     : -2146233087
            TargetObject          : '(deleted_at:null' is not a valid Falcon Query Language statement.
            CategoryInfo          : OperationStopped: ('(deleted_at:null' …Language statement.:String) [], RuntimeException
            FullyQualifiedErrorId : '(deleted_at:null' is not a valid Falcon Query Language statement.
            InvocationInfo        :
                ScriptLineNumber : 658
                OffsetInLine     : 17
                HistoryId        : -1
                ScriptName       : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Private\Private.ps1
                Line             : throw "'$_' is not a valid Falcon Query Language statement."

                PositionMessage  : At C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Private\Private.ps1:658 char:17
                                   + …             throw "'$_' is not a valid Falcon Query Language statemen …
                                   +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                PSScriptRoot     : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Private
                PSCommandPath    : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Private\Private.ps1
                CommandOrigin    : Internal
            ScriptStackTrace      : at <ScriptBlock>, C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Private\Private.ps1: line 658
                                    at Test-FqlStatement<Process>, C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Private\Private.ps1: line 655
                                    at <ScriptBlock>, C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\real-time-response.ps1: line 120
                                    at Get-FalconQueue<Process>, C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1: line 36
                                    at <ScriptBlock>, <No file>: line 1
        WasThrownFromThrowStatement : True
        TargetSite                  :
            Name          : CheckActionPreference
            DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.2.0.500, Culture=neutral,
PublicKeyToken=<Obscured>
            MemberType    : Method
            Module        : System.Management.Automation.dll
        Message                     : '(deleted_at:null' is not a valid Falcon Query Language statement.
        Data                        : System.Collections.ListDictionaryInternal
        InnerException              :
            Type                        : System.Management.Automation.RuntimeException
            ErrorRecord                 :
                Exception             :
                    Type    : System.Management.Automation.ParentContainsErrorRecordException
                    Message : '(deleted_at:null' is not a valid Falcon Query Language statement.
                    HResult : -2146233087
                CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
                FullyQualifiedErrorId : RuntimeException
            WasThrownFromThrowStatement : True
            Message                     : '(deleted_at:null' is not a valid Falcon Query Language statement.
            HResult                     : -2146233087
        Source                      : System.Management.Automation
        HResult                     : -2146233087
        StackTrace                  :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1
variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[]
args)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object
scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object
scriptThis, Object[] args)
   at System.Management.Automation.ValidateScriptAttribute.ValidateElement(Object element)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags
flags)
    Source                      : System.Management.Automation
    HResult                     : -2146233087
    StackTrace                  :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidData: (:) [Get-FalconSession], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationError,Get-FalconSession
InvocationInfo        :
    MyCommand        : Get-FalconSession
    ScriptLineNumber : 36
    OffsetInLine     : 43
    HistoryId        : 57
    ScriptName       : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1
    Line             : $Sessions = Get-FalconSession @SessionParam | Select-Object id, device_id

    PositionMessage  : At C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1:36 char:43
                       +             $Sessions = Get-FalconSession @SessionParam | Select-Obje …
                       +                                           ~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public
    PSCommandPath    : C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at Get-FalconQueue<Process>, C:\Users\<myusername>\Documents\PowerShell\Modules\psfalcon\2.1.5\Public\psf-real-time-response.ps1: line 36
                        at <ScriptBlock>, <No file>: line 1

Note: 
Rolling back version to 2.1.4 appears to work fine without issue.

**Comment by WEX-RMishler** [comment]
Duplicate of #139
